import { useEffect } from 'react';
import { ArrowLeft, CircleAlert, ExternalLink, LoaderCircle, Network, ShieldCheck } from 'lucide-react';
import { Link, useParams } from 'wouter';
import { getGetMirrorJobQueryKey, useGetMirrorJob } from '@workspace/api-client-react';

function PreviewSkeleton() {
  return <div className="mx-auto max-w-[1220px] animate-pulse px-5 py-8 md:px-10"><div className="h-4 w-28 rounded bg-[hsl(var(--muted))]" /><div className="mt-8 h-20 rounded-[1.35rem] bg-[hsl(var(--muted))]" /><div className="mt-6 h-[min(68dvh,720px)] rounded-[1.35rem] bg-[hsl(var(--muted))]" /></div>;
}

export default function MirrorPreviewPage() {
  const { id = '' } = useParams<{ id: string }>();
  const query = useGetMirrorJob(id, { query: { queryKey: getGetMirrorJobQueryKey(id), enabled: Boolean(id) } });
  const job = query.data && typeof query.data === 'object' && 'id' in query.data && 'status' in query.data ? query.data : undefined;
  const previewUrl = `/api/mirror-jobs/${encodeURIComponent(id)}/preview`;
  const canPreview = Boolean(job?.archiveAvailable && (job.status === 'completed' || job.status === 'completed_with_warnings'));
  useEffect(() => { document.title = job ? `Preview · ${(job.url ?? 'mirrored site').replace(/^https?:\/\//, '')}` : 'Mirror preview · Site Mirror'; }, [job]);

  if (query.isLoading) return <div className="min-h-[100dvh] bg-[hsl(var(--background))]"><PreviewSkeleton /></div>;
  if (query.error || !job) return <div className="flex min-h-[100dvh] items-center justify-center bg-[hsl(var(--background))] px-5"><div className="w-full max-w-md rounded-[1.4rem] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-7 text-center"><CircleAlert className="mx-auto h-6 w-6 text-[hsl(var(--destructive))]" /><h1 className="mt-5 text-xl font-extrabold">This preview is out of reach</h1><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">The mirror job could not be found or the control room is unavailable.</p><Link href={`/jobs/${encodeURIComponent(id)}`} className="mt-6 inline-flex h-10 items-center gap-2 rounded-xl bg-[hsl(var(--primary))] px-4 text-xs font-bold text-[hsl(var(--primary-foreground))]"><ArrowLeft className="h-3.5 w-3.5" />Back to job</Link></div></div>;
  if (!canPreview) return <div className="flex min-h-[100dvh] items-center justify-center bg-[hsl(var(--background))] px-5"><div className="text-center"><LoaderCircle className="mx-auto h-7 w-7 animate-spin text-[hsl(var(--primary))]" /><h1 className="mt-5 text-2xl font-extrabold">Preview will be ready soon</h1><p className="mt-3 text-sm text-[hsl(var(--muted-foreground))]">The archive must finish sealing before it can be played.</p><Link href={`/jobs/${encodeURIComponent(id)}`} className="mt-7 inline-flex h-10 items-center gap-2 rounded-xl bg-[hsl(var(--primary))] px-4 text-xs font-bold text-[hsl(var(--primary-foreground))]"><ArrowLeft className="h-3.5 w-3.5" />Back to job</Link></div></div>;

  return <div className="min-h-[100dvh] bg-[hsl(var(--background))]"><header className="border-b border-[hsl(var(--border))] bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]"><div className="mx-auto flex max-w-[1220px] items-center justify-between gap-4 px-5 py-4 md:px-10"><Link href={`/jobs/${encodeURIComponent(id)}`} className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[hsl(var(--accent))] text-[hsl(var(--accent-foreground))]"><Network className="h-4 w-4" /></span><span className="text-sm font-extrabold">site mirror</span></Link><span className="hidden items-center gap-2 font-mono text-[10px] uppercase tracking-[.14em] sm:flex"><ShieldCheck className="h-3.5 w-3.5 text-[hsl(var(--accent))]" />playable snapshot</span></div></header><main className="mx-auto max-w-[1220px] px-5 py-7 md:px-10"><div className="mb-5 flex flex-wrap items-center justify-between gap-4"><Link href={`/jobs/${encodeURIComponent(id)}`} className="inline-flex items-center gap-2 text-xs font-bold text-[hsl(var(--muted-foreground))]"><ArrowLeft className="h-3.5 w-3.5" />Back to job</Link><a href={previewUrl} target="_blank" rel="noopener noreferrer" className="inline-flex h-10 items-center gap-2 rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] px-4 text-xs font-bold text-[hsl(var(--primary))]"><ExternalLink className="h-3.5 w-3.5" />Open in new tab</a></div><section className="overflow-hidden rounded-[1.5rem] border border-[hsl(var(--border))] bg-[hsl(var(--card))] shadow-[var(--shadow-lg)]"><div className="border-b border-[hsl(var(--border))] px-5 py-5 md:px-7"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[hsl(var(--accent-foreground))]">Playable mirrored snapshot</p><h1 className="mt-2 truncate text-xl font-extrabold md:text-2xl">{job.url ?? 'Mirrored site'}</h1><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Keyboard, pointer lock, fullscreen, storage, audio, workers, WebAssembly, and local assets are enabled where supported by the browser.</p></div><div className="bg-[hsl(var(--muted)/.45)] p-2 sm:p-3"><iframe title={`Playable preview of ${job.url ?? 'mirrored site'}`} src={previewUrl} allow="accelerometer; autoplay; camera; fullscreen; gamepad; gyroscope; microphone; midi; payment; picture-in-picture; screen-wake-lock; speaker-selection; web-share; xr-spatial-tracking" sandbox="allow-downloads allow-forms allow-modals allow-orientation-lock allow-pointer-lock allow-popups allow-popups-to-escape-sandbox allow-presentation allow-same-origin allow-scripts" referrerPolicy="no-referrer" className="h-[min(78dvh,900px)] w-full rounded-xl border border-[hsl(var(--border))] bg-white" /></div></section></main></div>;
}
